name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Self test
        id: selftest
        uses: Bhupesh-V/moc@main
        with:
          username: "${{ github.actor }}"
      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add .
          git commit -m "Automated Commit: generate contributions file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true