name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Self test
        id: selftest
        uses: Bhupesh-V/moc@main
        with:
          username: "${{ github.actor }}"